"""
Nav2 stack for the multi-room world.

PREREQUISITE — generate the map first:
  ros2 launch go1sim_bringup slam.launch.py
  # drive the robot around with junior_ctrl until the map is complete
  ros2 run nav2_map_server map_saver_cli -f ~/multi_room_map
  # copy the .pgm and .yaml into go1sim_bringup/map_multi_room/
  #   cp ~/multi_room_map.pgm  <ws>/src/go1_resources/go1sim_bringup/map_multi_room/map.pgm
  #   cp ~/multi_room_map.yaml <ws>/src/go1_resources/go1sim_bringup/map_multi_room/map.yaml
  # rebuild: colcon build --packages-select go1sim_bringup

Usage (after map is saved and package rebuilt):
  ros2 launch go1sim_bringup navigation_multi_room.launch.py

Override map at runtime:
  ros2 launch go1sim_bringup navigation_multi_room.launch.py \\
      map:=/absolute/path/to/map.yaml
"""
import os
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.substitutions import FindPackageShare
from ament_index_python.packages import get_package_share_directory


def generate_launch_description():

    pkg = get_package_share_directory('go1sim_bringup')
    nav2_dir = FindPackageShare('nav2_bringup').find('nav2_bringup')
    nav2_launch_dir = os.path.join(nav2_dir, 'launch')

    # Default map — generated by SLAM and placed in map_multi_room/
    default_map = os.path.join(pkg, 'map_multi_room', 'map.yaml')
    nav2_params  = os.path.join(pkg, 'params', 'nav2_params_multi_room.yaml')
    bt_xml       = os.path.join(pkg, 'xml', 'go1_bt.xml')

    map_yaml     = LaunchConfiguration('map')
    use_sim_time = LaunchConfiguration('use_sim_time')
    autostart    = LaunchConfiguration('autostart')

    return LaunchDescription([
        DeclareLaunchArgument('map',          default_value=default_map),
        DeclareLaunchArgument('use_sim_time', default_value='True'),
        DeclareLaunchArgument('autostart',    default_value='true'),

        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(nav2_launch_dir, 'bringup_launch.py')),
            launch_arguments={
                'slam':                             'False',
                'map':                              map_yaml,
                'use_sim_time':                     use_sim_time,
                'params_file':                      nav2_params,
                'default_nav_to_pose_bt_xml':       bt_xml,
                'default_nav_through_poses_bt_xml': bt_xml,
                'autostart':                        autostart,
            }.items()),
    ])
